import type { Metadata } from "next";
import "leaflet/dist/leaflet.css";
import "./globals.css";
import { cookies } from "next/headers";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "../components/providers/theme-provider";
import { ActiveThemeProvider } from "../components/active-theme";
import HideNextIndicator from "../components/hideNextIndicator";
import { cn } from "../lib/utils";
import AppShell from "../components/AppShell";
import "leaflet/dist/leaflet.css";

export const metadata: Metadata = {
  title: "AUF-SARL",
  description: "Generated by create next app",
  icons: {
    icon: "logo.jpeg", // chemin depuis /public
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const activeThemeValue = cookieStore.get("active_theme")?.value;
  const isScaled = activeThemeValue?.endsWith("-scaled");

  return (
    <html lang="fr" suppressHydrationWarning>
      <body
        className={cn(
          "bg-background overscroll-none font-sans antialiased",
          activeThemeValue ? `theme-${activeThemeValue}` : "",
          isScaled ? "theme-scaled" : ""
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          enableColorScheme
        >
          <ActiveThemeProvider initialTheme={activeThemeValue}>
            <AppShell>{children}</AppShell>
            <Toaster position="top-right" />
            <HideNextIndicator />
          </ActiveThemeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
